version: 2
jobs:
  build:
    macos:
      xcode: 11.3.0
    working_directory: ~/repo
    environment:
      FL_OUTPUT_DIR: ~/output
    steps:
      # GLOBAL OPERATIONS

      # setup NPM
      - run: echo 'export PATH=~/npm_prefix/bin:$PATH' >> $BASH_ENV
      - run: npm config set prefix ~/npm_prefix

      # setup TNS
      # TODO: CACHE
      - run: npm i -g nativescript
      - run: tns usage-reporting disable
      - run: tns error-reporting disable

      # LOCAL OPERATIONS

      - checkout

      # NODE PACKAGES
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm rebuild
      - save_cache:
          # TODO: add platforms cache?
          paths:
            - node_modules
            - ~/.gradle/
          key: node-modules-{{ checksum "package-lock.json" }}

      # INSTALL GEMS (fastlane)
      #- restore_cache:
      #    key: gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - run: bundle show fastlane
      #- save_cache:
      #    key: gems-{{ checksum "Gemfile.lock" }}
      #    paths:
      #      - vendor/bundle

      - run:
          name: Fastlane
          command: bundle exec fastlane ios build

      # store artifacts
      - store_artifacts:
          path: ~/output
      - store_test_results:
          path: ~/output/scan

workflows:
  version: 2
  workflow:
    jobs:
      - build
