version: 2
jobs:
  build:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: echo Hello
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane ios build

workflows:
  version: 2
  workflow:
    jobs:
      - build
