fastlane_version '2.137.0'

platform :ios do
 before_all do
   setup_circle_ci
 end

 desc 'Build the iOS application.'
 lane :build do
    disable_automatic_code_signing(
      path: "./platforms/ios/cloudbuildstest.xcodeproj"
    )

    MY_APP_ID = "org.nativescript.tsApp1"
    MY_PROFILE = "match Development org.nativescript.tsApp1"
    MY_TEAM = "W7TGC3P93K"

    match(
        type: "development"
    )

    settings_to_override = {
      :PROVISIONING_PROFILE_SPECIFIER => MY_PROFILE,
    }

    gym(
      scheme: "cloudbuildstest",
      workspace: './platforms/ios/cloudbuildstest.xcworkspace',
      export_method: 'development',
      configuration: "Debug",
      xcargs: settings_to_override,
    )
 end

end